### ISSUE TITLE
Task 4.3 - Tracking changes and switching between versions

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/course-ds-base#13]
Branch: step-6-data-and-model-version-control
(continue from https://github.com/iterative/course-ds-base/issues/11) 

Tasks:
- [ ] add remote storage
- [ ] store `file.txt` to remote storage
- [ ] delete `file.txt` in workspace 
- [ ] restore `file.txt` from DVC cache with `dvc checkout file.txt`
- [ ] clean cache with `dvc gc`
- [ ] try to restore `file.txt` from DVC cache with `dvc checkout file.txt` (failure is expected)
- [ ] restore `file.txt` from DVC Remote Storage `dvc pull` (success is expected)
- [ ] update 'file.txt' (version 2) and push it to remote storage
- [ ] switch btw Git branches and 'file.txt' versions
