### ISSUE TITLE
Task 5.1 - Metrics Tracking with DVC

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/course-ds-base#15]
Branch: step-7-metrics-and-experiments

Tasks:
- [ ] save 'reports/metrics.json` file 
- [ ] specify `metrics` in `dvc.yaml` 
- [ ] `dvc metrics show` 
- [ ] `dvc metrics diff`
